authorName: Vincent
experimentName: ImageNetHB
trialConcurrency: 1
maxExecDuration: 20h
maxTrialNum: 150
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
advisor:
  builtinAdvisorName: Hyperband
  classArgs:
    R: 4
    eta: 3
    optimize_mode: maximize
trial:
  command: python train.py  --iter_size 1 --lr_sched exp  googlenet_bn-model-final.h5
  codeDir: .
  gpuNum: 1
