authorName: Vincent
experimentName: ImageNetTPE
trialConcurrency: 1
maxExecDuration: 90h
maxTrialNum: 150
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python train.py  --iter_size 1 --lr_sched exp  googlenet_bn
  codeDir: .
  gpuNum: 2
